config/routes.rb
ThelistIo::Application.routes.draw do

  root :to => "posts#index"

  match 'guidelines' => 'pages#guidelines'

  match 'docs' => 'pages#docs'

  match 'stats' => 'pages#stats'

  match 'blog' => 'pages#blog'

  match 'blog/downtime' => 'pages#blog2'

  match 'blog/api-status' => 'pages#blog1'

  match 'blog/v2' => 'pages#blog3'

  match 'user-levels' => 'pages#levels'

  match 'user/:username' => 'users#user'

  match 'applicants' => "requests#index"

  get "suggestions" => "suggestions#index"

  get "suggestions/new" => "suggestions#new"

  get "sessions/new"

  get 'posts/recent' => 'posts#recent', :as => "recent"

  get 'posts/top' => 'posts#top', :as => "top"

  get "signout" => "sessions#destroy", :as => "signout"

  get "signin" => "sessions#new", :as => "signin"

  get "gift" => "users#new", :as => "gift"

  get "redeem/:auth_token" => "users#update"

  get "apply" => "requests#new", :as => "apply"

  put "vote", :to => "vote#vote", as: :vote

  resources :users

  resources :sessions

  resources :posts do
    get 'page-:page', :action => :index, :on => :collection
    get 'fetch-title', :action => :fetch_title, :on => :collection
    get 'recent/page-:page', :action => :recent, :on => :collection
  end

  resources :comments

  resources :password_resets

  resources :requests

  resources :suggestions do
      get 'page-:page', :action => :index, :on => :collection
      get 'recent/page-:page', :action => :recent, :on => :collection
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  skip_before_filter :require_login

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Email sent with password reset instructions if account exists."
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update

    password_salt = BCrypt::Engine.generate_salt

    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes({
        :password_hash => BCrypt::Engine.hash_secret(params[:user][:password], password_salt),
  	  	:password_salt => password_salt
      })

      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h2>Reset Your Password</h2><br>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "problem") %> were found:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul><br>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div><br>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div><br>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<h2>Reset Your Password</h2><br>

<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div><br>
  <div class="actions"><%= submit_tag "Reset" %></div>
<% end %>