config/routes.rb
ThelistIo::Application.routes.draw do

  root :to => "posts#index"

  match 'guidelines' => 'pages#guidelines'

  match 'docs' => 'pages#docs'

  match 'stats' => 'pages#stats'

  match 'blog' => 'pages#blog'

  match 'blog/downtime' => 'pages#blog2'

  match 'blog/api-status' => 'pages#blog1'

  match 'blog/v2' => 'pages#blog3'

  match 'user-levels' => 'pages#levels'

  match 'user/:username' => 'users#user'

  match 'applicants' => "requests#index"

  get "suggestions" => "suggestions#index"

  get "suggestions/new" => "suggestions#new"

  get "sessions/new"

  get 'posts/recent' => 'posts#recent', :as => "recent"

  get 'posts/top' => 'posts#top', :as => "top"

  get "signout" => "sessions#destroy", :as => "signout"

  get "signin" => "sessions#new", :as => "signin"

  get "gift" => "users#new", :as => "gift"

  get "redeem/:auth_token" => "users#update"

  get "apply" => "requests#new", :as => "apply"

  put "vote", :to => "vote#vote", as: :vote

  resources :users

  resources :sessions

  resources :posts do
    get 'page-:page', :action => :index, :on => :collection
    get 'fetch-title', :action => :fetch_title, :on => :collection
    get 'recent/page-:page', :action => :recent, :on => :collection
  end

  resources :comments

  resources :password_resets

  resources :requests

  resources :suggestions do
      get 'page-:page', :action => :index, :on => :collection
      get 'recent/page-:page', :action => :recent, :on => :collection
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :downvotes, :post_id, :upvotes, :user_id, :comment_type

  validate :no_styles_scripts

  def no_styles_scripts
    errors.add(:base) if ["<style>","<script>","<title>","<!--"].any? { |a| body.include? a }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params[:comment].merge(:user_id => current_user.id))

    respond_to do |format|

      if @comment.comment_type == 0
  	  	model = Post
  	  	vote_type = 1
  	  elsif @comment.comment_type == 1
  	  	model = Suggestion
  	  	vote_type = 3
  	  end

      @post = model.find(@comment.post_id)

	    if @comment.save

	    	@mixpanel = Mixpanel::Tracker.new "15c792135a188f39a0b6875a46a28d74"
    	  @mixpanel.track 'comment', { :username => current_user.username }



    	  @new_vote = Vote.new(:post_id => @comment.id, :user_id => current_user.id, :vote_type => vote_type, :direction => 0, :value => 0)

    	  @new_vote.save

        format.html { redirect_to @comment.comment_type == 1 ? @post : @post }
        format.json { render json: @comment.comment_type == 1 ? @post : @post, status: :created }
      else
        format.html { redirect_to @comment.comment_type == 1 ? @post : @post, :flash => { :notice => "Nice try." } }
      end
	  end
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br />
    <%= f.number_field :comment_id %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :upvote %><br />
    <%= f.number_field :upvote %>
  </div>
  <div class="field">
    <%= f.label :downvote %><br />
    <%= f.number_field :downvote %>
  </div>
  <div class="actions">
    <%= f.submit "Post Comment" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @comment.text %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @comment.comment_id %>
</p>

<p>
  <b>Parent:</b>
  <%= @comment.parent_id %>
</p>

<p>
  <b>Upvote:</b>
  <%= @comment.upvote %>
</p>

<p>
  <b>Downvote:</b>
  <%= @comment.downvote %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>