config/routes.rb
ThelistIo::Application.routes.draw do

  root :to => "posts#index"

  match 'guidelines' => 'pages#guidelines'

  match 'docs' => 'pages#docs'

  match 'stats' => 'pages#stats'

  match 'blog' => 'pages#blog'

  match 'blog/downtime' => 'pages#blog2'

  match 'blog/api-status' => 'pages#blog1'

  match 'blog/v2' => 'pages#blog3'

  match 'user-levels' => 'pages#levels'

  match 'user/:username' => 'users#user'

  match 'applicants' => "requests#index"

  get "suggestions" => "suggestions#index"

  get "suggestions/new" => "suggestions#new"

  get "sessions/new"

  get 'posts/recent' => 'posts#recent', :as => "recent"

  get 'posts/top' => 'posts#top', :as => "top"

  get "signout" => "sessions#destroy", :as => "signout"

  get "signin" => "sessions#new", :as => "signin"

  get "gift" => "users#new", :as => "gift"

  get "redeem/:auth_token" => "users#update"

  get "apply" => "requests#new", :as => "apply"

  put "vote", :to => "vote#vote", as: :vote

  resources :users

  resources :sessions

  resources :posts do
    get 'page-:page', :action => :index, :on => :collection
    get 'fetch-title', :action => :fetch_title, :on => :collection
    get 'recent/page-:page', :action => :recent, :on => :collection
  end

  resources :comments

  resources :password_resets

  resources :requests

  resources :suggestions do
      get 'page-:page', :action => :index, :on => :collection
      get 'recent/page-:page', :action => :recent, :on => :collection
  end

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  attr_accessible :comment_count, :text, :title, :user_id
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  skip_before_filter :require_login, :only => [:index, :show, :recent, :top]

  @@suggestions = Suggestion
    .joins("LEFT JOIN votes ON suggestions.id = votes.post_id")
    .select("suggestions.id," +
      "sum(if(vote_type = 2, if(direction = 0, value, -value),0)) as score," +
      "sum(if(vote_type = 2, if(direction = 0, value, 0),0)) as upvotes," +
      "sum(if(vote_type = 2, if(direction = 1, -value, 0),0)) as downvotes," +
      "suggestions.created_at," +
      "text," +
      "title," +
      "suggestions.user_id")
    .group("suggestions.id")

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = @@suggestions.order("sum(if(vote_type = 2, if(direction = 0, value, -value),0)) DESC, suggestions.created_at DESC")
      .page(@page)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suggestions }
    end
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
    @suggestion = Suggestion.find(params[:id])

    @comments = Comment
      .joins("LEFT JOIN votes ON comments.id = votes.post_id")
      .select("comments.id," +
        "sum(if(vote_type = 3, if(direction = 0, value, if(direction is null, 0, -value)),0)) as score," +
        "sum(if(vote_type = 3, if(direction = 0, value, 0),0)) as upvotes," +
        "sum(if(vote_type = 3, if(direction = 1, -value, 0),0)) as downvotes," +
        "comments.created_at," +
        "body," +
        "comments.user_id")
      .where(:post_id => @suggestion.id, :comment_type => 1)
      .group("comments.id")

    @comment = Comment.new

    @suggestion = Suggestion
      .joins("LEFT JOIN votes ON suggestions.id = votes.post_id")
      .select("suggestions.id," +
        "sum(if(vote_type = 2, if(direction = 0, value, if(direction is null, 0, -value)),0)) as score," +
        "sum(if(vote_type = 2, if(direction = 0, value, 0),0)) as upvotes," +
        "sum(if(vote_type = 2, if(direction = 1, -value, 0),0)) as downvotes," +
        "suggestions.created_at," +
        "text," +
        "title," +
        "suggestions.user_id")
      .find(params[:id])

    if current_user
      if Vote.where(:user_id => current_user.id, :post_id => @suggestion.id, :direction => 0, :vote_type => 2).count > 0
        @active = ' upactive'
      elsif Vote.where(:user_id => current_user.id, :post_id => @suggestion.id, :direction => 1, :vote_type => 2).count > 0
        @active = ' downactive'
      end

      found_vote = Vote.find_by_post_id_and_user_id_and_vote_type(@suggestion.id, current_user.id, 3)

      if found_vote
        @value = found_vote.value
      else
     	  @value = current_user.karma * 0.02
     	  @value = 1 if @value < 1
      end


      if current_user.id == @suggestion.user_id.to_i
        @active += " owner"
      end
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @suggestion }
    end
  end

  # GET /suggestions/new
  # GET /suggestions/new.json
  def new
    @suggestion = Suggestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @suggestion }
    end
  end

  # GET /suggestions/1/edit
  def edit
    @suggestion = Suggestion.find(params[:id])
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(params[:suggestion].merge(:user_id => current_user.id))

    respond_to do |format|
      if @suggestion.save

   	    @new_vote = Vote.create(:post_id => @suggestion.id, :user_id => current_user.id, :vote_type => 2, :direction => 0, :value => 1)

        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully created.' }
        format.json { render json: @suggestion, status: :created, location: @suggestion }
      else
        format.html { render action: "new" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /suggestions/1
  # PUT /suggestions/1.json
  def update
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      if @suggestion.update_attributes(params[:suggestion])
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion = Suggestion.find(params[:id])
    @suggestion.destroy

    respond_to do |format|
      format.html { redirect_to suggestions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper

  def comment_count(post_id, comment_type)
  	amount = Comment.where(:post_id => post_id, :comment_type => comment_type).count
  	
  	if amount == 0
  		"Leave a Comment"
  	elsif amount == 1
  		"View 1 Comment"
  	else
  		"View " + amount.to_s + " Comments"
  	end
  end

end

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div><br>
  <div class="field">
    <%= f.label :text, "Additional Information" %><br />
    <%= f.text_field :text %>
  </div><br>
  <div class="actions">
    <%= f.submit "Add Suggestion" %>
  </div>
<% end %>

app/views/suggestions/index.html.erb
<h2>Suggestions</h2>
<p>The List is a community driven website. <%= link_to "Suggest a feature here.", new_suggestion_path  %></p><br>

<% if @suggestions.count == {} %>
  No suggestions at the moment.
<% end %>

<ol>
  <% @suggestions.each_with_index do |suggestion, i| %>

    <%
      if current_user
        if Vote.find_by_user_id_and_post_id_and_direction_and_vote_type(current_user.id, suggestion.id, 0, 2)
          active = 'upactive'
        elsif Vote.find_by_user_id_and_post_id_and_direction_and_vote_type(current_user.id, suggestion.id, 1, 2)
          active = 'downactive'
        end

        found_vote = Vote.find_by_post_id_and_user_id_and_vote_type(suggestion.id, current_user.id, 2)

        if found_vote
          value = found_vote.value
        else
       	  value = current_user.karma * 0.02
       	  value = 1 if value < 1
        end
        if current_user.id == suggestion.user_id.to_i
          active += " owner"
        end
      end
    %>

    <li>
<!--
      <div class="order">
        <span><%= i + 1 %>.</span>
      </div>
-->
      <div class="suffrage <%= active %>" data-value="<%= value %>">
        <% if current_user %>
          <%= link_to '&#9650;'.html_safe, vote_path(:post_id => suggestion.id, :vote_type => 2, :direction => 0, :value => value), :remote => true, :method => "put", :class => "up" %>
        <% else %>
          <%= link_to '&#9650;'.html_safe, signin_path, :class => "up" %>
        <% end %>
        <br>
        <span data-total="<%= suggestion.score.to_i %>" data-up="+<%= suggestion.upvotes.to_i %>" data-down="<%= suggestion.downvotes.to_i %>"><%= suggestion.score.to_i %></span><br>
        <% if current_user %>
          <%= link_to '&#9660;'.html_safe, vote_path(:post_id => suggestion.id, :vote_type => 2, :direction => 1, :value => value), :remote => true, :method => "put", :class => "down" %>
        <% else %>
          <%= link_to '&#9660;'.html_safe, signin_path, :class => "down" %>
        <% end %>
        <br>
      </div>
      <div class="submission">
        <div class="submission-inner">
          <%= link_to suggestion.title, suggestion, :class => "title" %><br>
          <span class="meta">Suggested by <%= link_to User.find(suggestion.user_id).username, { :controller => "users", :action => "user", :username => User.find(suggestion.user_id).username.downcase }, { :class => ("red" if User.find(suggestion.user_id).karma > 100) } %>&nbsp;&mdash;&nbsp;<%= time_ago_in_words(suggestion.created_at) %> ago&nbsp;&mdash;&nbsp;<%= link_to comment_count(suggestion.id, 1), suggestion %></span>
        </br>
      </div>
    </li>
  <% end %>
</ol>
<br><br>

app/views/suggestions/new.html.erb
<h2>New Suggestion</h2>
<%= link_to "&larr; Back to Suggestions".html_safe, suggestions_path %>

<%= render 'form' %>

app/views/suggestions/show.html.erb
<h2>Suggestions</h2>
<%= link_to "&larr; Back to Suggestions".html_safe, suggestions_path %><br><br>
<div class="show-li">
  <div class="suggestion-suffrage suffrage<%= @active %>" data-value="<%= @value %>">
    <% if current_user %>
      <%= link_to '&#9650;'.html_safe, vote_path(:post_id => @suggestion.id, :vote_type => 2, :direction => 0, :value => @value), :remote => true, :method => "put", :class => "up" %>
    <% else %>
      <%= link_to '&#9650;'.html_safe, signin_path, :class => "up" %>
    <% end %>
    <br>
    <span data-total="<%= @suggestion.score.to_i %>" data-up="+<%= @suggestion.upvotes.to_i %>" data-down="<%= @suggestion.downvotes.to_i %>"><%= @suggestion.score.to_i %></span><br>
    <% if current_user %>
      <%= link_to '&#9660;'.html_safe, vote_path(:post_id => @suggestion.id, :vote_type => 2, :direction => 1, :value => @value), :remote => true, :method => "put", :class => "down" %>
    <% else %>
      <%= link_to '&#9660;'.html_safe, signin_path, :class => "down" %>
    <% end %>
    <br>
  </div>

  <h2 class="title"><%= @suggestion.title %></h2><br>
  <h3>Additional Information:</h3>
  <p><%= @suggestion.text %></p>
  <span class="meta">Suggested by <a href="/user/<%= User.find(@suggestion.user_id).username.downcase %>"><%= User.find(@suggestion.user_id).username %></a>&nbsp;&mdash;&nbsp;<%= time_ago_in_words(@suggestion.created_at) %> ago.<br></span>
</div>
<% @comments.each do |c| %>

  <%
    if current_user
      if Vote.find_by_user_id_and_post_id_and_direction_and_vote_type(current_user.id, c.id, 0, 3)
        comment_active = 'upactive'
      elsif Vote.find_by_user_id_and_post_id_and_direction_and_vote_type(current_user.id, c.id, 1, 3)
        comment_active = 'downactive'
      end

      found_vote = Vote.find_by_post_id_and_user_id_and_vote_type(c.id, current_user.id, 3)

      if found_vote
        comment_value = found_vote.value
      else
     	  comment_value = current_user.karma * 0.02
     	  comment_value = 1 if comment_value < 1
      end

      if current_user.id == c.user_id.to_i
        comment_active = comment_active.to_s + " owner"
      end

    end
  %>

  <div class="comment">
    <div class="comment-meta">
      <div class="suffrage <%= comment_active %>" data-value="<%= comment_value %>">
        <% if current_user %>
          <%= link_to '&#9650;'.html_safe, vote_path(:post_id => c.id, :vote_type => 3, :direction => 0, :value => comment_value), :remote => true, :method => "put", :class => "up" %><br>
        <% else %>
          <%= link_to '&#9650;'.html_safe, signin_path, :class => "up" %>
        <% end %>
        <span data-total="<%= c.score.to_i %>" data-up="+<%= c.upvotes.to_i %>" data-down="<%= c.downvotes.to_i %>"><%= c.score.to_i %></span><br>
        <% if current_user %>
          <%= link_to '&#9660;'.html_safe, vote_path(:post_id => c.id, :vote_type => 3, :direction => 1, :value => comment_value), :remote => true, :method => "put", :class => "down" %><br>
        <% else %>
          <%= link_to '&#9660;'.html_safe, signin_path, :class => "down" %>
        <% end %>
      </div>

      <img src="http://www.gravatar.com/avatar/<%= Digest::MD5.hexdigest(User.find(c.user_id).email) %>?d=http%3A%2F%2Fthelist.io%2Fassets%2Fprofile.jpg&s=200" class="comment-photo" /><br>

      <a href="/user/<%= User.find(c.user_id).username %>" class="<%= "red" if (detect_level(c.user_id) == 4) %>"><b><%= User.find(c.user_id).username %></b></a>
      <span class="meta">Written <%= time_ago_in_words(c.created_at) %> ago.<br></span>
    </div>
  	<div class="comment-body"><%= markdown(c.body) %></div>
  	<div class="quote">Quote</div>
	</div><br>
<% end %>

<% if current_user %>
   <%= render :partial => 'posts/newcomment' %>
<% end %>