config/routes.rb
ThelistIo::Application.routes.draw do

  root :to => "posts#index"

  match 'guidelines' => 'pages#guidelines'

  match 'docs' => 'pages#docs'

  match 'stats' => 'pages#stats'

  match 'blog' => 'pages#blog'

  match 'blog/downtime' => 'pages#blog2'

  match 'blog/api-status' => 'pages#blog1'

  match 'blog/v2' => 'pages#blog3'

  match 'user-levels' => 'pages#levels'

  match 'user/:username' => 'users#user'

  match 'applicants' => "requests#index"

  get "suggestions" => "suggestions#index"

  get "suggestions/new" => "suggestions#new"

  get "sessions/new"

  get 'posts/recent' => 'posts#recent', :as => "recent"

  get 'posts/top' => 'posts#top', :as => "top"

  get "signout" => "sessions#destroy", :as => "signout"

  get "signin" => "sessions#new", :as => "signin"

  get "gift" => "users#new", :as => "gift"

  get "redeem/:auth_token" => "users#update"

  get "apply" => "requests#new", :as => "apply"

  put "vote", :to => "vote#vote", as: :vote

  resources :users

  resources :sessions

  resources :posts do
    get 'page-:page', :action => :index, :on => :collection
    get 'fetch-title', :action => :fetch_title, :on => :collection
    get 'recent/page-:page', :action => :recent, :on => :collection
  end

  resources :comments

  resources :password_resets

  resources :requests

  resources :suggestions do
      get 'page-:page', :action => :index, :on => :collection
      get 'recent/page-:page', :action => :recent, :on => :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The List — A Social Knowledge Board</title>
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag(:rss, "http://thelist.io/posts/recent.rss") %>
  <link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.ico">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "modernizr" %>
  <% if Date.today.month == 4 && Date.today.day == 1 %>
    <style>
      body {
        -webkit-transform: rotate(3deg);
        -moz-transform: rotate(3deg);
        -o-transform: rotate(3deg);
        -ms-transform: rotate(3deg);
        transform: rotate(3deg);
        overflow-x: hidden;
      }
    </style>
  <% end %>
</head>
<body>
  <div class="wrap">
    <header>
      <section>
        <h1><a href="/">The List</a></h1>
        <div class="meta-header">
          <% if current_user %>
            <%= link_to current_user.username + " (Level " + detect_level(current_user).to_s + ")", { :controller => "users", :action => "user", :username => current_user.username.downcase } %>
            <span>&nbsp;&bull;&nbsp;</span>
            <%= link_to 'Recent', recent_path %>
            <span>&nbsp;&bull;&nbsp;</span>
            <%= link_to 'Submit', new_post_path %>
            <span>&nbsp;&bull;&nbsp;</span>
            <%= link_to 'Invite', gift_path %>
            <span>&nbsp;&bull;&nbsp;</span>
            <%= link_to "Sign Out", signout_path %>
          <% else %>
         	  <%= link_to 'Sign Up', apply_path %>
         	  <span>&nbsp;&bull;&nbsp;</span>
            <%= link_to 'Top', top_path %>
            <span>&nbsp;&bull;&nbsp;</span>
            <%= link_to 'Recent', recent_path %>
            <span>&nbsp;&bull;&nbsp;</span>
            <%= link_to 'About', docs_path %>
            <span>&nbsp;&bull;&nbsp;</span>
            <%= link_to "Sign In", signin_path %>
          <% end %>
        </div>
      </section>
    </header>
    <section>
      <% flash.each do |name, msg| %>
    	   <%= content_tag :div, msg, :id => "flash_#{name}" %><br>
    	<% end %>
      <%= yield %>
    </section>
  </div>
  <footer>
    <style>
      /* Responsiveness */

      @media only screen and (max-width: 650px), only screen and (min-device-width: 320px) and (max-device-width: 480px) {
        .wrap > header {
          line-height: normal;
          text-align: center;
        }

        .meta-header a {
          line-height: 40px;
        }

        body > footer > section {
          text-align: center;
          padding-top: 15px;
          padding-bottom: 15px;
          line-height: 30px;
        }

        h1 {
          display: block;
          width: 100%;
          text-align: center;
          position: static;
        }

        .wrap > header > section {
          padding-top: 10px;
          padding-bottom: 20px;
        }
      }
    </style>
    <%= javascript_include_tag "application" %>
  <section>
    <%= link_to "Suggestions", '/suggestions' %>
    <span>&nbsp;&bull;&nbsp;</span>
    <%= link_to 'Top', top_path %>
    <span>&nbsp;&bull;&nbsp;</span>
    <%= link_to "Levels", '/user-levels' %>
    <span>&nbsp;&bull;&nbsp;</span>
    <%= link_to "RSS", '/posts/recent.rss' %>
    <span>&nbsp;&bull;&nbsp;</span>
    <%= link_to "Guidelines", '/guidelines' %>
    <span>&nbsp;&bull;&nbsp;</span>
    <%= link_to "Applicants", '/applicants' %>
    <span>&nbsp;&bull;&nbsp;</span>
    <%= link_to "Blog", '/blog' %>
    <span>&nbsp;&bull;&nbsp;</span>
    <%= link_to "Bookmarklet", "javascript:window.open(%22http://thelist.io/posts/new?u=%22+encodeURIComponent(document.location)+%22&t=%22+encodeURIComponent(document.title))", :id => "bookmarklet" %>
    <span>&nbsp;&bull;&nbsp;</span>
    <%= link_to 'About', docs_path %>
    <span>&nbsp;&bull;&nbsp;</span>
    <%= link_to 'Contact', "mailto:personal@jacksongariety.com,colby@aley.me?subject=The%20List%20Inquiry" %>
  </section>
  <script src="http://hashtraffic.com/js/hashtraffic-desktop.js"></script>
  </footer>
  <script type="text/javascript">
    var GoSquared = {};
    GoSquared.acct = "GSN-530677-Y";
    (function(w){
      function gs(){
        w._gstc_lt = +new Date;
        var d = document, g = d.createElement("script");
        g.type = "text/javascript";
        g.src = "//d1l6p2sc9645hc.cloudfront.net/tracker.js";
        var s = d.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(g, s);
      }
      w.addEventListener ?
        w.addEventListener("load", gs, false) :
        w.attachEvent("onload", gs);
    })(window);
  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-29461279-4', 'thelist.io');
    ga('send', 'pageview');

  </script>
<div id="dragme">Drag me.</div>
</body>
</html>